version: 0.0
os: linux
files:
  - source: build/libs/ROOT.war
    destination: /data/war/web/
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
permissions:
  - object: scripts/deploy.sh
    pattern: "**"
    owner: root
    mode: 755
    type:
      - file
